format = """
[](#9A348E)\
$username\
[](fg:#9A348E bg:#DA627D)\
$directory\
[](fg:#DA627D bg:#33658A)\
$git_branch\
$git_status\
[](fg:#33658A bg:#519DC7)\
$nodejs\
$rust\
[](fg:#519DC7)\

$line_break\
[](#b80000)\
$time\
[ ](fg:#b80000)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#33658A"
format = '[[ $symbol $branch ](bg:#33658A)]($style)'

[git_status]
style = "bg:#33658A"
format = '[[($all_status$ahead_behind )](bg:#33658A)]($style)'

[nodejs]
symbol = ""
style = "bg:#519DC7"
format = '[[ $symbol ($version) ](bg:#519DC7)]($style)'

[rust]
symbol = ""
style = "bg:#519DC7"
format = '[[ $symbol ($version) ](bg:#519DC7)]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#b80000"
format = '[[ ♥ $time ](bg:#b80000)]($style)'

[line_break]
disabled = false